table dim_hour

	column 'N° heure'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: hour

	column Heure
		dataType: string
		summarizeBy: none
		sourceColumn: hour_label
		sortByColumn: 'N° heure'

	column 'Créneau'
		dataType: string
		summarizeBy: none
		sourceColumn: time_slot

	partition dim_hour = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents(DossierDonnees & "dim_hour.parquet")),
				    Typed = Table.TransformColumnTypes(Source, {{"hour", Int64.Type}, {"hour_label", type text}, {"time_slot", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
